### ISSUE TITLE
Patents have multiple numbers: add (+) button to enable to add those numbers

### ISSUE THREAD

**Issue by jangenoe** [citation-style-language/zotero-bits#81]
Patents have multiple numbers, typically one for each country where the patent is filed. 

Please add a (+) button, similar to the "author" or "inventor" field to enable to add those additional patent number fields. For those who do not use multiple patent numbers, or prefer to have a different database entry for each subsequent filing, it does not make any difference adding a plus button. They still can continue as they do now.

When merging two or more patents with different patent number, all numbers should be kept.

**Comment by karnesky** [comment]
I believe that those patents are very much distinct documents, though (e.g. WO2016171675A1 is a separate application from US20180130636A1, so will have different dates and possibly some other minute differences).  See also the handling of different editions for other item types.

These are very closely related, of course.  But this would seem to call for adding more interfacial complexity (e.g. to capture each relevant date) because it is a fundamentally different data model than Zotero uses.

I've also seen no style guidelines for citing multiple patent numbers for a single "invention" in a bibliography. Do you have examples or suggestions on how these should be processed?

**Comment by jangenoe** [comment]
I agree that there should style guide for citing a single "invention" (i.e. a patent family)  in a bibliography. What now happens is that a single invention is cited multiple times using a different patent number.
I would prefer that, in such a style guide, the first filing would be the reference filing, and the other patent numbers could be linked as subsequent filings.
If these documents should be as multiple documents in the Zotero database, which I understand as they are unique, though often minor differences, would there be a way to link or group them in Zotero such that when citing a patent family, the first filing or a selected/preferred filing is inserted in the (word) document.

**Comment by karnesky** [comment]
Just for clarity: neither the Zotero project nor the CSL community author style guides. If there is no existing style (maintained by a third-party organization or publisher), the odds of implementing something like this seem low.

**Comment by bwiernik** [comment]
Yes, this is out of scope for either Zotero or CSL. Patents with different numbers are distinct documents. Absent a style guide requiring they be cited as one item, I don't see CSL supporting citing multiple patents as one item.
