### ISSUE TITLE
Allow page to be valid field for book

### ISSUE THREAD

**Issue by mvolz** [citation-style-language/zotero-bits#84]
Page does not appear to be a valid book type, but for our use case it would be useful. It's an ongoing complaint for us  that Google books links, which include the page as a query parameter, doesn't end up in the citation. https://phabricator.wikimedia.org/T160848

I know there's  probably use cases where it makes sense NOT to include the page, but might be worth at least having the field?

**Comment by adam3smith** [comment]
The Zotero data model distinguishes between an item and a citation. If you think about it in the context of academic writing, you would cite a book, potentially multiple times, with different page numbers, across a single article (each of these a citation). You would then only include one single entry to the book (the item), without any page number, in the bibliography.

"Page" as the CSL variable is intended to describe the item as a whole. It's a page range and as such doesn't typically make sense for a book.

For citations, Zotero/CSL have the concept of a locator, which is specific to a given citation (and can be of different types: page, chapter, column, verse, etc.). That would seem to correspond to the google book page here. Since it's specific to a citation, it makes no sense to extract that information when importing an item -- I'm afraid allowing this will cause more problems than it solves. 

I'm not sure if Citoid could be made to work around this for its purposes.

**Comment by karnesky** [comment]
In the CSL data model, this is usually addressed by having a locator (a cite-specific pinpointer within the item). In the Zotero workflow, this tends to be entered by a user manually when they make an individual citation. In many bibliographic styles, this means the book will appear only once in the bibliography, but individual citations tlcan refer to unique pages within the book. There have been occasional requests to Zotero to make it easier to add notes referring to a particular page (from e.g. an attached note or a file that may represent a limited number of pages).

Zotero has a separate type, book section, that includes a page range. Sections tend to be more than one page and I would assert that storing Google books as book sections with a single page reference is not the expected behavior.

There are multiple citation/location/bibliography styles in use on Wikipedia. Which ones is this feature request trying to address and would implementing this feature not break all styles that separate locators (e.g. a section of footnotes containing a short citation ang page number) from the bibliography?

**Comment by mvolz** [comment]
I figured something similar was the case, but thanks for the detailed response!
